
services:
  server:
    build:
      context: .
    container_name: nest-server
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}   # Neon DB URL from .env
    ports:
      - "3333:5000"
    networks:
      - dev-network
    volumes:
      - .:/dist
    working_dir: /dist
    command: ["npm", "run", "start:prod"]

  prisma:
    image: node:20-alpine
    container_name: prisma-cli
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - dev-network
    environment:
      DATABASE_URL: ${DATABASE_URL}   # Neon DB URL
    entrypoint: ["npx", "prisma",]     # You can override commands like "migrate" or "studio"
    tty: true                         # Keep container running for interactive CLI

networks:
  dev-network:
    driver: bridge
